### ISSUE TITLE
Which slot is which?

### ISSUE THREAD

**Issue by HyperMan19680** [LatvianModder/Transistor#1]
I never even heard of the Transistor game on Steam til today, so I have NO idea what I am doing. For starters, can we get an idea which slot on the transistor is for what? Maybe also a list of what each item does in the Transistor GUI?

**Comment by LatvianModder** [comment]
If you check out latest file on CurseForge it now lists what effects item has (most of them obviously not implemented) and what slot its used in. I updated the description anyway
